package main

import (
	"context"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/kube-actions-runner/kube-actions-runner/internal/config"
	"github.com/kube-actions-runner/kube-actions-runner/internal/discovery"
	ghclient "github.com/kube-actions-runner/kube-actions-runner/internal/github"
	"github.com/kube-actions-runner/kube-actions-runner/internal/k8s"
	"github.com/kube-actions-runner/kube-actions-runner/internal/logger"
	"github.com/kube-actions-runner/kube-actions-runner/internal/scaler"
	"github.com/kube-actions-runner/kube-actions-runner/internal/tokens"
	"github.com/kube-actions-runner/kube-actions-runner/internal/webhook"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func main() {
	log := logger.New()

	cfg, err := config.Load()
	if err != nil {
		log.Error("failed to load configuration", "error", err)
		os.Exit(1)
	}

	// Create token registry
	tokenRegistry, err := tokens.NewRegistry(cfg.GitHubTokens, cfg.GitHubToken)
	if err != nil {
		log.Error("failed to create token registry", "error", err)
		os.Exit(1)
	}

	// Log configured owners
	if tokenRegistry.HasMultipleTokens() {
		log.Info("token registry initialized with multiple owners",
			"owners", tokenRegistry.GetConfiguredOwners(),
			"has_default", tokenRegistry.HasDefaultToken(),
		)
	} else if tokenRegistry.HasDefaultToken() {
		log.Info("token registry initialized with single default token")
	} else {
		owners := tokenRegistry.GetConfiguredOwners()
		if len(owners) > 0 {
			log.Info("token registry initialized with single owner", "owner", owners[0])
		}
	}

	labelMatchers := scaler.ParseLabelMatchers(cfg.LabelMatchers)

	// Create K8s client early - needed for webhook secret persistence
	k8sClient, err := k8s.NewClient(cfg.Namespace)
	if err != nil {
		log.Error("failed to create Kubernetes client", "error", err)
		os.Exit(1)
	}

	// Determine webhook secret (may be auto-generated and persisted)
	webhookSecret := cfg.WebhookSecret
	secretIsNew := false

	// Handle webhook auto-registration
	var webhookManager *webhook.Manager
	var reconciler *scaler.Reconciler // Declared here for goroutine access, initialized later
	if cfg.WebhookAutoRegister {
		log.Info("webhook auto-registration enabled",
			"webhook_url", cfg.WebhookURL,
			"sync_interval", cfg.WebhookSyncInterval,
		)

		// If no webhook secret configured, try to load from K8s or generate new one
		if cfg.WebhookSecret == "" {
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			existingSecret, err := k8sClient.GetWebhookSecret(ctx)
			cancel()

			if err != nil {
				log.Error("failed to retrieve webhook secret from Kubernetes", "error", err)
				os.Exit(1)
			}

			if existingSecret != "" {
				log.Info("using persisted webhook secret from Kubernetes")
				webhookSecret = existingSecret
			} else {
				// Will be generated by webhook manager and we'll persist it
				secretIsNew = true
			}
		}

		webhookManager, err = webhook.NewManager(webhook.Config{
			TokenRegistry: tokenRegistry,
			WebhookURL:    cfg.WebhookURL,
			WebhookSecret: webhookSecret, // Pass existing or empty for generation
			Logger:        log,
		})
		if err != nil {
			log.Error("failed to create webhook manager", "error", err)
			os.Exit(1)
		}

		// Use the (possibly generated) secret
		webhookSecret = webhookManager.GetWebhookSecret()

		// Persist newly generated secret to Kubernetes
		if secretIsNew {
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			if err := k8sClient.SaveWebhookSecret(ctx, webhookSecret); err != nil {
				log.Error("failed to persist webhook secret to Kubernetes", "error", err)
				os.Exit(1)
			}
			cancel()
			log.Info("persisted new webhook secret to Kubernetes")
		}

		// Run initial discovery and registration in background
		// Pass secretIsNew to force update all webhooks when secret was just generated
		go func(forceUpdate bool, rec *scaler.Reconciler) {
			if forceUpdate {
				log.Info("starting initial webhook sync in background (forcing updates - new secret)")
			} else {
				log.Info("starting initial webhook sync in background")
			}
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
			defer cancel()

			discoverer := discovery.NewDiscoverer(tokenRegistry, log)
			results, err := webhookManager.SyncWebhooks(ctx, discoverer, forceUpdate)
			if err != nil {
				log.Error("initial webhook sync failed", "error", err)
				return
			}

			var created, updated, unchanged, errors int
			var discoveredRepos []string
			for _, r := range results {
				if r.Created {
					created++
				}
				if r.Updated {
					updated++
				}
				if r.Unchanged {
					unchanged++
				}
				if r.Error != nil {
					errors++
				}
				// Collect repos with self-hosted workflows for reconciler
				discoveredRepos = append(discoveredRepos, r.Repo)
			}
			log.Info("initial webhook sync complete",
				"created", created,
				"updated", updated,
				"unchanged", unchanged,
				"errors", errors,
			)

			// Update reconciler with discovered repos
			if rec != nil && len(discoveredRepos) > 0 {
				rec.SetReposToCheck(discoveredRepos)
			}
		}(secretIsNew, reconciler)
	}

	log.Info("starting kube-actions-runner",
		"namespace", cfg.Namespace,
		"port", cfg.Port,
		"label_matchers", cfg.LabelMatchers,
		"runner_mode", cfg.RunnerMode,
		"runner_image", cfg.RunnerImage,
		"job_ttl_seconds", cfg.TTLSeconds,
		"runner_group_id", cfg.RunnerGroupID,
		"webhook_auto_register", cfg.WebhookAutoRegister,
		"skip_node_check", cfg.SkipNodeCheck,
		"reconciler_enabled", cfg.ReconcilerEnabled,
		"reconciler_interval", cfg.ReconcilerInterval,
		"reconciler_active_interval", cfg.ReconcilerActiveInterval,
		"reconciler_inactivity_window", cfg.ReconcilerInactivityWindow,
	)

	ghClientFactory := ghclient.NewClientFactory(tokenRegistry, cfg.RunnerGroupID)

	s := scaler.NewScaler(scaler.Config{
		WebhookSecret:   []byte(webhookSecret),
		LabelMatchers:   labelMatchers,
		GHClientFactory: ghClientFactory,
		K8sClient:       k8sClient,
		Logger:          log,
		RunnerMode:      cfg.RunnerMode,
		RunnerImage:     cfg.RunnerImage,
		DindImage:       cfg.DindImage,
		TTLSeconds:      cfg.TTLSeconds,
		SkipNodeCheck:   cfg.SkipNodeCheck,
	})

	// Start reconciler to pick up orphaned queued jobs
	var reconcilerCancel context.CancelFunc
	if cfg.ReconcilerEnabled {
		reconciler = scaler.NewReconciler(scaler.ReconcilerConfig{
			GHClientFactory:  ghClientFactory,
			K8sClient:        k8sClient,
			Scaler:           s,
			Logger:           log,
			Interval:         cfg.ReconcilerInterval,
			ActiveInterval:   cfg.ReconcilerActiveInterval,
			InactivityWindow: cfg.ReconcilerInactivityWindow,
			LabelMatchers:    labelMatchers,
		})

		var reconcilerCtx context.Context
		reconcilerCtx, reconcilerCancel = context.WithCancel(context.Background())
		go reconciler.Start(reconcilerCtx)
	}

	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Recoverer)
	r.Use(middleware.Timeout(10 * time.Second))

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})
	r.Get("/ready", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})
	r.Handle("/metrics", promhttp.Handler())
	r.Post("/webhook", s.HandleWebhook)

	srv := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  30 * time.Second,
	}

	// Start periodic webhook sync if enabled
	stopSync := make(chan struct{})
	if cfg.WebhookAutoRegister && cfg.WebhookSyncInterval > 0 {
		go func() {
			ticker := time.NewTicker(cfg.WebhookSyncInterval)
			defer ticker.Stop()

			discoverer := discovery.NewDiscoverer(tokenRegistry, log)

			for {
				select {
				case <-ticker.C:
					log.Info("running periodic webhook sync")
					ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
					results, err := webhookManager.SyncWebhooks(ctx, discoverer, false)
					cancel()

					if err != nil {
						log.Error("periodic webhook sync failed", "error", err)
					} else {
						var created, updated, unchanged, errors int
						for _, r := range results {
							if r.Created {
								created++
							}
							if r.Updated {
								updated++
							}
							if r.Unchanged {
								unchanged++
							}
							if r.Error != nil {
								errors++
							}
						}
						if created > 0 || updated > 0 || errors > 0 {
							log.Info("periodic webhook sync complete",
								"created", created,
								"updated", updated,
								"unchanged", unchanged,
								"errors", errors,
							)
						}
					}
				case <-stopSync:
					return
				}
			}
		}()
	}

	go func() {
		log.Info("server listening", "addr", srv.Addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	// Stop the sync goroutine
	close(stopSync)

	// Stop the reconciler
	if reconcilerCancel != nil {
		reconcilerCancel()
	}

	log.Info("shutting down server")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Error("server forced to shutdown", "error", err)
		os.Exit(1)
	}

	log.Info("server stopped")
}
